services:
  app:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: bloglist-frontend-dev
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api/
    depends_on:
      - server
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
  server:
    image: express-server-exercise-dev
    build:
      context: ./bloglist-backend
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./bloglist-backend:/usr/src/app
    container_name: bloglist-backend
    environment:
      PORT: 3001
      MONGODB_URI: mongodb+srv://Dennis:<redacted-password>@cluster0.t7xp1js.mongodb.net/bloglistApp?retryWrites=true&w=majority
